In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("data.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [3]:
df["tenure"].max()
df["tenure"].min()

0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.drop(columns=["customerID"],inplace=True)

In [7]:
df["TotalCharges"]=pd.to_numeric(df["TotalCharges"],errors="coerce")

In [8]:
df["tenure"]=pd.cut(df["tenure"],bins=[0,12,24,48,100],labels=["High Chances","Chances","low Chances","very low chances"],include_lowest=True)

In [9]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [10]:
df["TotalCharges"].isnull().sum()/len(df["TotalCharges"])

0.001561834445548772

In [11]:
df["TotalCharges"].skew()

0.961642499724251

In [13]:
df["InternetService"].unique()
df["InternetService_used"]=df["InternetService"].map({"No":"No","Fiber optic":"Yes","DSL":"Yes"})

In [15]:
df["MultipleLines"].unique()
df["MultipleLines"]=df["MultipleLines"].map({"No phone service":"No","Yes":"Yes","No":"No"})

In [16]:
service=["PhoneService","MultipleLines","InternetService_used","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]
df["Services"]=df[service].eq("Yes").sum(axis=1)

In [17]:
df["Services"]

0       2
1       4
2       4
3       4
4       2
       ..
7038    8
7039    7
7040    2
7041    3
7042    7
Name: Services, Length: 7043, dtype: int64

In [18]:
df[service]

,PhoneService,MultipleLines,InternetService_used,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,No,No,Yes,No,Yes,No,No,No,No
1,Yes,No,Yes,Yes,No,Yes,No,No,No
2,Yes,No,Yes,Yes,Yes,No,No,No,No
3,No,No,Yes,Yes,No,Yes,Yes,No,No
4,Yes,No,Yes,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...
7038,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes
7039,Yes,Yes,Yes,No,Yes,Yes,No,Yes,Yes
7040,No,No,Yes,Yes,No,No,No,No,No
7041,Yes,Yes,Yes,No,No,No,No,No,No
7042,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes

In [19]:
df["Churn"]=df["Churn"].map({"Yes":1,"No":0})

In [20]:
df["risk"]=((df["tenure"].eq("High Chances")) & (df["Contract"]=="Month-to-month")).astype(int)

In [21]:
df.groupby("tenure")["Contract"].value_counts()

C:\Users\mukul_xblv51q\AppData\Local\Temp\ipykernel_4368\1088168128.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("tenure")["Contract"].value_counts()

tenure            Contract
High Chances      Month-to-month    1994
                  One year           124
                  Two year            68
Chances           Month-to-month     737
                  One year           197
                  Two year            90
low Chances       Month-to-month     802
                  One year           518
                  Two year           274
very low chances  Two year          1263
                  One year           634
                  Month-to-month     342
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gender                7043 non-null   object
 1   SeniorCitizen         7043 non-null   int64
 2   Partner               7043 non-null   object
 3   Dependents            7043 non-null   object
 4   tenure                7043 non-null   category
 5   PhoneService          7043 non-null   object
 6   MultipleLines         7043 non-null   object
 7   InternetService       7043 non-null   object
 8   OnlineSecurity        7043 non-null   object
 9   OnlineBackup          7043 non-null   object
 10  DeviceProtection      7043 non-null   object
 11  TechSupport           7043 non-null   object
 12  StreamingTV           7043 non-null   object
 13  StreamingMovies       7043 non-null   object
 14  Contract              7043 non-null   object
 15  PaperlessBilling      7043 non-null   object
 16  PaymentMethod         7043 non-null   object
 17  MonthlyCharges        7043 non-null   float64
 18  TotalCharges          7032 non-null   float64
 19  Churn                 7043 non-null   int64
 20  InternetService_used  7043 non-null   object
 21  Services              7043 non-null   int64
 22  risk                  7043 non-null   int32
dtypes: category(1), float64(2), int32(1), int64(3), object(16)
memory usage: 1.2+ MB

In [23]:
df["Partner"] = df["Partner"].str.strip().str.capitalize()
df["Dependents"] = df["Dependents"].str.strip().str.capitalize()

In [24]:
df["Partner"] = df["Partner"].map({"Yes": 1, "No": 0})
df["Dependents"] = df["Dependents"].map({"Yes": 1, "No": 0})
df["family_present"]=(df["SeniorCitizen"]+df["Partner"]+df["Dependents"])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gender                7043 non-null   object
 1   SeniorCitizen         7043 non-null   int64
 2   Partner               7043 non-null   int64
 3   Dependents            7043 non-null   int64
 4   tenure                7043 non-null   category
 5   PhoneService          7043 non-null   object
 6   MultipleLines         7043 non-null   object
 7   InternetService       7043 non-null   object
 8   OnlineSecurity        7043 non-null   object
 9   OnlineBackup          7043 non-null   object
 10  DeviceProtection      7043 non-null   object
 11  TechSupport           7043 non-null   object
 12  StreamingTV           7043 non-null   object
 13  StreamingMovies       7043 non-null   object
 14  Contract              7043 non-null   object
 15  PaperlessBilling      7043 non-null   object
 16  PaymentMethod         7043 non-null   object
 17  MonthlyCharges        7043 non-null   float64
 18  TotalCharges          7032 non-null   float64
 19  Churn                 7043 non-null   int64
 20  InternetService_used  7043 non-null   object
 21  Services              7043 non-null   int64
 22  risk                  7043 non-null   int32
 23  family_present        7043 non-null   int64
dtypes: category(1), float64(2), int32(1), int64(6), object(14)
memory usage: 1.2+ MB

In [26]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,InternetService_used,Services,risk,family_present
0,Female,0,1,0,High Chances,No,No,DSL,No,Yes,...,Month-to-month,Yes,Electronic check,29.85,29.85,0,Yes,2,1,1
1,Male,0,0,0,low Chances,Yes,No,DSL,Yes,No,...,One year,No,Mailed check,56.95,1889.50,0,Yes,4,0,0
2,Male,0,0,0,High Chances,Yes,No,DSL,Yes,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,1,Yes,4,1,0
3,Male,0,0,0,low Chances,No,No,DSL,Yes,No,...,One year,No,Bank transfer (automatic),42.30,1840.75,0,Yes,4,0,0
4,Female,0,0,0,High Chances,Yes,No,Fiber optic,No,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,1,Yes,2,1,0

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
encode=["gender","tenure","InternetService","Contract","PaperlessBilling","PaymentMethod"]
encode=encode+service
print(encode)

['gender', 'tenure', 'InternetService', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'PhoneService', 'MultipleLines', 'InternetService_used', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

In [28]:
preprocessing=ColumnTransformer(transformers=[("encoding",OneHotEncoder(drop="first",handle_unknown="ignore"),encode),("impute",SimpleImputer(strategy="median"),["TotalCharges"])],remainder="passthrough")

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,recall_score,precision_score,classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression

In [31]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=["Churn"]),df["Churn"],random_state=42,test_size=0.25,stratify=df["Churn"])

In [265]:
import dagshub

dagshub.init(repo_owner='Mukul9112003', repo_name='project3_Telecom_Customer_Churn_Prediction_System', mlflow=True)
mlflow.set_experiment(experiment_name="handle imbalance")

with mlflow.start_run():
  pipeline=Pipeline(steps=[
    ("pre",preprocessing),
    ("model",LogisticRegression(class_weight="balanced"))
  ])
  pipeline.fit(X_train,Y_train)
  predict=pipeline.predict(X_test)
  accuracy=accuracy_score(Y_test,predict)
  precision=precision_score(Y_test,predict)
  recall=recall_score(Y_test,predict)
  confusion=confusion_matrix(Y_test,predict)
  report=classification_report(Y_test,predict)
  mlflow.log_metric('accuracy_score',accuracy)
  mlflow.log_metric('precision_score',precision)
  mlflow.log_metric('recall_score',recall)

Initialized MLflow to track repo "Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System"

Repository Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System initialized!

2026/04/21 12:43:31 INFO mlflow.tracking.fluent: Experiment with name 'handle imbalance' does not exist. Creating a new experiment.
c:\Users\mukul_xblv51q\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

🏃 View run angry-kite-711 at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1/runs/76c90246ab5e4216ab72bd643013baff
🧪 View experiment at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1

In [266]:
from sklearn.ensemble import RandomForestClassifier
with mlflow.start_run():
  pipeline=Pipeline(steps=[
    ("pre",preprocessing),
    ("model",RandomForestClassifier(class_weight="balanced"))
  ])
  pipeline.fit(X_train,Y_train)
  predict=pipeline.predict(X_test)
  accuracy=accuracy_score(Y_test,predict)
  precision=precision_score(Y_test,predict)
  recall=recall_score(Y_test,predict)
  confusion=confusion_matrix(Y_test,predict)
  report=classification_report(Y_test,predict)
  mlflow.log_metric('accuracy_score',accuracy)
  mlflow.log_metric('precision_score',precision)
  mlflow.log_metric('recall_score',recall)

🏃 View run gaudy-yak-536 at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1/runs/7e19ad1cd0ab4b319c71116a1d4eec24
🧪 View experiment at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1

In [267]:
from xgboost import XGBClassifier
with mlflow.start_run():
  scale_pos_weight=len(Y_train[Y_train==0])/len(Y_train[Y_train==1])
  pipeline=Pipeline(steps=[
    ("pre",preprocessing),
    ("model",XGBClassifier(scale_pos_weight=scale_pos_weight))
  ])
  pipeline.fit(X_train,Y_train)
  predict=pipeline.predict(X_test)
  accuracy=accuracy_score(Y_test,predict)
  precision=precision_score(Y_test,predict)
  recall=recall_score(Y_test,predict)
  confusion=confusion_matrix(Y_test,predict)
  report=classification_report(Y_test,predict)
  mlflow.log_metric('accuracy_score',accuracy)
  mlflow.log_metric('precision_score',precision)
  mlflow.log_metric('recall_score',recall)

🏃 View run incongruous-vole-365 at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1/runs/87420d7de69d468fb80afbe53ca25771
🧪 View experiment at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1

In [ ]:
import numpy as np
import mlflow
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, precision_recall_curve
)
from xgboost import XGBClassifier

neg = (Y_train == 0).sum()
pos = (Y_train == 1).sum()
scale_pos_weight = neg / pos if pos != 0 else 1

with mlflow.start_run():
    pipeline = Pipeline(steps=[
        ("pre", preprocessing),
        ("model", XGBClassifier(
            eval_metric="logloss",
            scale_pos_weight=scale_pos_weight,
            use_label_encoder=False
        ))
    ])

    param_grid = {
        "model__n_estimators": [100, 200],
        "model__max_depth": [3, 5],
        "model__learning_rate": [0.01, 0.1]
    }

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=5,
        n_jobs=-1,
        scoring="f1"   
    )

    grid.fit(X_train, Y_train)
    best = grid.best_estimator_

    probs = best.predict_proba(X_test)[:, 1]

    thresholds = np.arange(0.1, 0.9, 0.01)

    best_thresh = 0.5
    best_f1 = 0

    for t in thresholds:
        preds = (probs > t).astype(int)
        f1 = f1_score(Y_test, preds)

        if f1 > best_f1:
            best_f1 = f1
            best_thresh = t

    print("Best Threshold:", best_thresh)
    print("Best F1:", best_f1)

    final_pred = (probs > best_thresh).astype(int)

    accuracy = accuracy_score(Y_test, final_pred)
    precision = precision_score(Y_test, final_pred)
    recall = recall_score(Y_test, final_pred)
    auc = roc_auc_score(Y_test, probs)

    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1", best_f1)
    mlflow.log_metric("roc_auc", auc)
    mlflow.log_metric("best_cv_score", grid.best_score_)

    mlflow.log_param("threshold", best_thresh)
    mlflow.log_params(grid.best_params_)

    mlflow.sklearn.log_model(best, "model")

c:\Users\mukul_xblv51q\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:200: UserWarning: [15:20:30] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best Threshold: 0.48999999999999977
Best F1: 0.6610025488530161

2026/04/21 15:20:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/21 15:20:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run useful-squid-134 at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1/runs/022c2b1ca57e4f16ae9344c7e29b6218
🧪 View experiment at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/1

In [32]:
X_train,X_val,Y_train,Y_val=train_test_split(X_train,Y_train,random_state=42,test_size=0.20,stratify=Y_train)

In [42]:

import dagshub
import mlflow
from sklearn.metrics import accuracy_score,recall_score,precision_score,classification_report,confusion_matrix,precision_recall_curve,roc_auc_score
from xgboost import XGBClassifier
dagshub.init(repo_owner='Mukul9112003', repo_name='project3_Telecom_Customer_Churn_Prediction_System', mlflow=True)
mlflow.set_experiment(experiment_name="Final experiment")
with mlflow.start_run():
    neg = (Y_train == 0).sum()
    pos = (Y_train == 1).sum()
    scale_pos_weight = neg / pos
    pipeline=Pipeline(steps=[
        ("preprocessing",preprocessing),
        ("model",XGBClassifier(scale_pos_weight=scale_pos_weight,eval_metric="logloss",use_label_encoder=False))
        ]
        )
    grid={
        "model__n_estimators": [100, 200],
        "model__max_depth": [3, 5],
        "model__learning_rate": [0.01, 0.1]
    }
    grid=GridSearchCV(estimator=pipeline,param_grid=grid,cv=5,scoring="f1")
    grid.fit(X_train,Y_train)
    grid.fit(X_train, Y_train)
    best = grid.best_estimator_

    probs = best.predict_proba(X_val)[:, 1]
    precision,recall,thresholds=precision_recall_curve(Y_val,probs)
    f1=(2*precision*recall)/(precision+recall)
    best_idx=np.argmax(f1)
    best_thresh=thresholds[best_idx]
    best_f1=f1[best_idx]
    print("Best Threshold:", best_thresh)
    print("Best F1:", best_f1)
    probs=best.predict_proba(X_test)[:, 1]
    final_pred = (probs > best_thresh).astype(int)

    accuracy = accuracy_score(Y_test, final_pred)
    precision = precision_score(Y_test, final_pred)
    recall = recall_score(Y_test, final_pred)
    auc = roc_auc_score(Y_test, probs)

    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1", best_f1)
    mlflow.log_metric("roc_auc", auc)
    mlflow.log_metric("best_cv_score", grid.best_score_)

    mlflow.log_param("threshold", best_thresh)
    mlflow.log_params(grid.best_params_)

    mlflow.sklearn.log_model(best, "model")

Initialized MLflow to track repo "Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System"

Repository Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System initialized!

Best Threshold: 0.5944873
Best F1: 0.6666666666666666

2026/04/22 11:20:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/22 11:20:18 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run sassy-bird-332 at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/2/runs/b8040429683a45d2b26b79be33d8a229
🧪 View experiment at: https://dagshub.com/Mukul9112003/project3_Telecom_Customer_Churn_Prediction_System.mlflow/#/experiments/2